### ISSUE TITLE
./llamavid/processor/clip-patch14-224  not found

### ISSUE THREAD

**Issue by wh0x** [dvlab-research/LLaMA-VID#1]

**Comment by yanwei-li** [comment]
Sorry about the missing file. They have been uploaded. Please try it again.

**Comment by yanwei-li** [comment]
Close it now, please reopen it if you have further questions.

**Comment by FangXinyu-0913** [comment]
Can you provide the link directly? I haven't found the corresponding file in README. Thank you very much for your answer
