### ISSUE TITLE
Question about Vision Encoder EVA-G

### ISSUE THREAD

**Issue by FuryMartin** [dvlab-research/LLaMA-VID#13]
In the LLaMA-VID paper, I noticed that the Vision Encoder is mentioned as `EVA-G`, which is attributed to the work of _Yuxin Fang, Wen Wang, Binhui Xie, Quan Sun, Ledell Wu, Xinggang Wang, Tiejun Huang, Xinlong Wang, and Yue Cao in their paper titled "Eva: Exploring the limits of masked visual representation learning at scale," published in CVPR 2023._ 

However, upon reviewing EVA's [paper](https://arxiv.org/abs/2211.07636) and [GitHub repository](https://github.com/baaivision/EVA), I couldn't find any reference to `EVA-G`. I'm unsure if this is a typographical error or if "EVA-G" is an older name for EVA. Could you kindly assist me in clarifying this question?

**Comment by yanwei-li** [comment]
Hi, `EVA-G` here indicates the `ViT-g/14` from [EVA-CLIP](https://arxiv.org/abs/2303.15389). Because we adopt the pre-trained QFormer from [InstructBLIP](http://arxiv.org/abs/2305.06500), we also kept the same visual encoder (EVA-CLIP with ViT-g/14) to keep the same features. Sorry for the confusion.

**Comment by FuryMartin** [comment]
> Hi, `EVA-G` here indicates the `ViT-g/14` from [EVA-CLIP](https://arxiv.org/abs/2303.15389). Because we adopt the pre-trained QFormer from [InstructBLIP](http://arxiv.org/abs/2305.06500), we also kept the same visual encoder (EVA-CLIP with ViT-g/14) to keep the same features. Sorry for the confusion

Got it. Thanks for your reply.
