### ISSUE TITLE
Where to donwload MSVD-QA dataset for evaluation?

### ISSUE THREAD

**Issue by Felix0805** [dvlab-research/LLaMA-VID#14]
Hello,

Thanks a lot for your great work. I would like to ask how can I download LLaMA-VID-Eval/MSVD-QA/video and LLaMA-VID-Eval/MSVD-QA/test_qa.json for evaluation?

**Comment by wcy1122** [comment]
Hello. You can download these files from [here](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155186668_link_cuhk_edu_hk/EUNEXqg8pctPq3WZPHb4Fd8BYIxHO5qPCnU6aWsrV1O4JQ?e=ZurbUg)

**Comment by Felix0805** [comment]
I really appreciate it.
