### ISSUE TITLE
There is no get_videos method in conversation.py

### ISSUE THREAD

**Issue by zyghome** [dvlab-research/LLaMA-VID#16]
It seems that the video conversation not implemented yet? In gradio_web_server.py there are several calling for state.get_videos(), but there is none in class Conversation

**Comment by yjzst** [comment]
Same question

**Comment by yanwei-li** [comment]
Thanks for this report. We add this function in Conversation. Please pull the code and try it again.

**Comment by yanwei-li** [comment]
Please open the issue again if you have further questions.
