### ISSUE TITLE
Can't Download shot detection results

### ISSUE THREAD

**Issue by Deaddawn** [dvlab-research/LLaMA-VID#17]
Hi, there. The link you give for short detection res get a little problem, could you check it?

**Comment by Deaddawn** [comment]
https://answers.microsoft.com/en-us/msoffice/forum/all/were-sorry-but-cant-be-found-in-the-sharepointcom/399fcb08-5e6f-41ab-a1b5-26849ac182ac, could you please check this problem, i get the exact same.

**Comment by liziming5353** [comment]
Have you solved it? I also meet this problem.

**Comment by Deaddawn** [comment]
> Have you solved it? I also meet this problem.

Yes, you can check movienet original paper
