### ISSUE TITLE
Hi Yanwei,This is my contact request

### ISSUE THREAD

**Issue by MathewWuZJ** [dvlab-research/LLaMA-VID#21]
I tried to contact you by email, but I did not get a response. It is not sure whether it is because the email was not successfully delivered or my meaning was not accurate. May I ask if I can contact you on WeChat?

**Comment by yanwei-li** [comment]
Sorry, I did not receive any email, maybe you can send another one to (ywli AT cse.cuhk.edu.hk). Thanks!

**Comment by MathewWuZJ** [comment]
HI YW,It seems that I can't contact you by email, maybe the email was accidentally processed into spam, or some other uncontrollable factors. Here is my wechat account: wzjtzuens. If it is convenient for you, please kindly contact me.
