### ISSUE TITLE
关于stage2的json文件

### ISSUE THREAD

**Issue by liziming5353** [dvlab-research/LLaMA-VID#22]
请问你们stage2做微调的时候是默认使用llava_v1_5_mix665k_with_video_chatgpt_maxtime_5min.json这个文件吗？如果是的话，为什么要把视频限制在5分钟以内呢？

**Comment by yanwei-li** [comment]
It's the default one for the model with vicuna 13B (the one for 7B without time limit), because we need to avoid the out-of-memory problem during training if the video is too long.

**Comment by liziming5353** [comment]
请问有预估需要多少内存吗？如果我的内存够用，是不是就不用限制5分钟了呢

**Comment by yanwei-li** [comment]
Hi, for vicuna 7B, it requires <40G in my experiments, and 80G for vicuna 13B.

**Comment by liziming5353** [comment]
Thanks! Also, may I ask how much loss can you get in stages 1, 2, and 3? I want to check if my training is correct. Now in stage 1 I get loss=2 and in stage 2 I get loss=1

**Comment by yanwei-li** [comment]
Hi, the loss for stages 1, 2, and 3 is about 1.9~2.1, 0.8~1.0 , 1.3~1.5, respectively.

**Comment by liziming5353** [comment]
Got it!
