### ISSUE TITLE
Failed to run finetuning stage2 with ActivityNet videos

### ISSUE THREAD

**Issue by XenonLamb** [dvlab-research/LLaMA-VID#23]
Great work! I have an issue when trying to run the short video finetuning stage 2:
Although I manually checked the ActivityNet videos I downloaded are in mp4 format and is playable, I received the errors like
`Error in loading 374062, retrying...                                                                                                                                                      
Error in loading 370984, retrying...                                                                                                                                                      
Error in loading 416357, retrying...                                                                                                                                                      
Error in loading 407613, retrying...                                                                                                                                                      
Error in loading 397054, retrying...                                                                                                                                                      
Error in loading 400911, retrying...                                                                                                                                                      
[h264 @ 0x561a1edabac0] Missing reference picture, default is 65530                                                                                                                       
[h264 @ 0x561a4b9d0f40] mmco: unref short failure                                                                                                                                         
[h264 @ 0x561a4b9d0f40] mmco: unref short failure                                                                                                                                         
[h264 @ 0x561a1edabac0] Missing reference picture, default is 65530                                                                                                                       
[h264 @ 0x561a4b9d0f40] mmco: unref short failure                                                                                                                                         
[h264 @ 0x561a4b9d0f40] mmco: unref short failure                                                                                                                                         
[h264 @ 0x55c33946bfc0] mmco: unref short failure                                                                                                                                         
[h264 @ 0x55c33946bfc0] mmco: unref short failure                                                                                                                                         
[h264 @ 0x55c33946bfc0] mmco: unref short failure                                                                                                                                         
[h264 @ 0x55c33946bfc0] mmco: unref short failure                                                                                                                                         
Error in loading 414902, retrying...                                                                                                                                                      
Error in loading 375344, retrying...   `
I'm not very familiar with the video decoding protocols. Any suggestions on how this happens and what we should to to fix it is appreciated. Thank you!

**Comment by yanwei-li** [comment]
Hi, if there are too many warnings like `Error in loading xxxx`, it could be strange and you may need to debug to find if the video file is missing. And for the warning ` [h264 @ 0x561a4b9d0f40] mmco: unref short failure`, we also find such warnings in video processing and we just ignore it.
