### ISSUE TITLE
Demo Crash

### ISSUE THREAD

**Issue by QiSu77** [dvlab-research/LLaMA-VID#25]
Hi, when i using the demo page your great team provided, I find that even a video which is more than 1min will leads to the page crash. Which is as same as what happens when I doing inference, what is strange is that  there is no error reported on my terminal. 
So I think it maybe something general, did you ever meet it? 
Could you please try it on the demo page provided to have more know about it

**Comment by wcy1122** [comment]
Hi. I have deleted some files on my local server and restarted the online demo.
In my test, the online demo looks fine now for more than 1 minute video.
Maybe you can try again on our online demo.

**Comment by QiSu77** [comment]
@wcy1122 Oh, you are my hero!  Can you tell me more details about the files you deleted? Where are they in the Structure which the official provides, and what are their names.  Thank you  very much!

**Comment by wcy1122** [comment]
Hi, thanks for your interest in our work.
I found that the code will dump uploaded videos to `/tmp/gradio` in my local server, but the memory of which is limited. I just deleted these files and restarted the demo. Not sure if you face the same problem.

**Comment by QiSu77** [comment]
Thank you ! 
I want to know where can I download "llama-vid-vicuna-7b-short" model.
I just find  "llama-vid-7b-full-224-video-fps-1" and "llama-vid-13b-full-224-video-fps-1"  for short video.

**Comment by wcy1122** [comment]
Hi. "llama-vid-vicuna-7b-short" is the same model as "llama-vid-7b-full-224-video-fps-1", we rename the folder.

**Comment by QiSu77** [comment]
Thank you very much!
