### ISSUE TITLE
我想在不训练的情况下，使用长视频推断，请问长数据的数据推理的格式是什么？

### ISSUE THREAD

**Issue by kunkunsheng** [dvlab-research/LLaMA-VID#31]
![image](https://github.com/dvlab-research/LLaMA-VID/assets/86947725/f10c3ce1-8451-40aa-a604-c890a55e0dc0)
这video和files的文件格式好像具体说明，请问有没有下载网页的链接，或者格式说明

**Comment by wcy1122** [comment]
Hi. You can follow [this section](https://github.com/dvlab-research/LLaMA-VID?tab=readme-ov-file#preparation) to download MovieNet from [here](https://opendatalab.com/OpenDataLab/MovieNet/tree/main/raw) and additional shot detection results from [here]() for inference. 
The script in your screenshot is to pre-compute the CLIP features and subtitles for training and inference. You can set `video_dir` as the data root of the folder of `movie1K.keyframes.240p.v1.zip`, and `files_dir` as the data root of the folder of `MovieNet.tar.gz`.

**Comment by kunkunsheng** [comment]
> Hi. You can follow [this section](https://github.com/dvlab-research/LLaMA-VID?tab=readme-ov-file#preparation) to download MovieNet from [here](https://opendatalab.com/OpenDataLab/MovieNet/tree/main/raw) and additional shot detection results from [here](https://mycuhk-my.sharepoint.com/personal/1155186668_link_cuhk_edu_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F1155186668%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2FLLaMA%2DVID%2Fshot%2Ezip&parent=%2Fpersonal%2F1155186668%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2FLLaMA%2DVID&ga=1) for inference.
> 
> The script in your screenshot is to pre-compute the CLIP features and subtitles for training and inference. You can set `video_dir` as the data root of the folder of `movie1K.keyframes.240p.v1.zip`, and `files_dir` as the data root of the folder of `MovieNet.tar.gz`.
> 
> After feature pre-processing, you can follow this script to inference, setting `video-file` as the processed feature.
> 
> > python llamavid/serve/run_llamavid_movie.py 
> >     --model-path work_dirs/llama-vid/llama-vid-7b-full-224-long-video 
> >     --video-file  
> >     --load-4bit

好的，谢谢你，如果我在此基础上，上传单个自己的视频应该怎么做提取特征进行推断呢，

**Comment by wcy1122** [comment]
Hi. We have updated the script for customized video pre-processing. It will use CLIP to extract video features and use OpenAI Whisper to obtain subtitles. You can run this script

> python scripts/extra_tool/extract_video_features_subtitles.py \
    --video_file <path to customized video> \
    --feat_dir <path to output features>
