### ISSUE TITLE
An code error

### ISSUE THREAD

**Issue by liziming5353** [dvlab-research/LLaMA-VID#32]
In line 430 in llamavid_arch.py, the judgment criteria should be if images[0].shape[0] > 1000. images[0].shape[-1] is always 224.

**Comment by yanwei-li** [comment]
Hi, 224 is for raw image input, if the long video is preprocessed with image encoder, the last dimension is 1408.

**Comment by liziming5353** [comment]
I am still puzzled. 1408 is the output dim of eva_vit. The 'images' in line 430 have not been feed to eva_vit,  so the last dimension must be 224, right？

**Comment by yanwei-li** [comment]
Hi, for long video, we first extract features of the raw image using eva_vit that is loaded from local file at [this line](https://github.com/dvlab-research/LLaMA-VID/blob/688390cf62fa7d24b4236c69bbb9f3c9ae829f82/llamavid/train/train.py#L894C27-L894C27).

**Comment by liziming5353** [comment]
I see. Thank you!
