### ISSUE TITLE
Questions about checkpoint loading

### ISSUE THREAD

**Issue by zhangbw17** [dvlab-research/LLaMA-VID#33]
Thank you for your work, but I'm facing some problems when using the command line for inference. I would greatly appreciate your assistance. I use this cmd, 

> `python -m llamavid.serve.cli --model-path work_dirs/llama-vid/llama-vid-7b-full-224-video-fps-1 --image-file <path to your video> --temperature 0.5`

and got a lot of output about unexpected keys and missing keys like
> Some weights of the model checkpoint at work-dirs/llama-vid/llama-vid-7b-full-224-video-fps-1 were not used when initializing LlavaLlamaAttForCausalLM: ['model.vision_tower.vision_tower.blocks.20.norm2.bias', 'model.vision_tower.vision_tower.blocks.31.attn.proj.bias', ...

> unexpected_keys=['norm.weight', 'norm.bias', 'head.weight', 'head.bias', 'blocks.39.norm1.weight'

and
> Some weights of BertLMHeadModel were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['bert.encoder.layer.11.output_query.LayerNorm.bias', 'bert.encoder.layer.6.crossattention.self.query.weight', ...

Also, compared to the web demo, the quality of the results from the command line is much lower using the same parameter. Could the loading of the model be the cause of this issue?
Looking forward to your reply, thanks!

**Comment by yanwei-li** [comment]
Hi, the warnings are normal because the model is post initialized. We align the `cli` settings with that in the web demo, please pull and try it again. Moreover, we use 4bit with `--load-4bit` for the demo.

**Comment by zhangbw17** [comment]
Thank you very much, I'll give it a try.
