### ISSUE TITLE
May I ask if the format of the video file inferred from long videos is the format after feature extraction? Why do I always report errors and cannot recognize video information

### ISSUE THREAD

**Issue by kunkunsheng** [dvlab-research/LLaMA-VID#34]
![image](https://github.com/dvlab-research/LLaMA-VID/assets/86947725/ea3de637-a1f4-4448-a38a-9f7674573a15)
--video-file ./feat_dir/tt0032138.pkl  The file is fully calculated and extracted based on long video inference
![image](https://github.com/dvlab-research/LLaMA-VID/assets/86947725/37445332-aa28-41e6-983e-0304d32a8418)

**Comment by wcy1122** [comment]
Hi. You may change `--question Summarize video information` to `--question 'summarize video information'`

**Comment by kunkunsheng** [comment]
> Hi. You may change `--question Summarize video information` to `--question 'summarize video information'`

Hello, I would like to ask if increasing the sampling rate of long videos can reduce the memory occupied by model inference. Because I use 
extra_tool/extract_video_features_subtitles.py 
file for inference, 
it shows that my 3090 24g memory is not enough. I am asking for the def load to increase the video sampling rateb sample avoid this situation.

**Comment by wcy1122** [comment]
Yes, increasing the sampling rate results in fewer input tokens for LLMs, thereby reducing the GPU memory.
Meanwhile, if you have more than one 3090 GPU on the same machine, you may try multi-GPU inference, which use model parallel to save GPU memory.
