### ISSUE TITLE
whether able to inference long video without using subtitles?

### ISSUE THREAD

**Issue by Deaddawn** [dvlab-research/LLaMA-VID#38]
Hi, there. I am wondering is it possible to inference long video just like short videos without using subtitles?

**Comment by yanwei-li** [comment]
Hi, of course, you can infer long videos without subtitles. But in this case, the model cannot know the name of each character and what happens exactly in the video along the timeline. It may cause it to answer questions like "a man is doing xxx and then he xxx", which may lose the storyline of this video.
