### ISSUE TITLE
multiple json for training?

### ISSUE THREAD

**Issue by dragen1860** [dvlab-research/LLaMA-VID#39]
Dear author:
   Thanks for pulishing the great work.
   I noticed both in stage 1&2, the paper need to train on several datasets, hence it need to specify multiple json file in training script. However, in `stage_1_2_full_v7b_224_fps_1.sh`, i find only single json dataset file are used to train for each stage. I wonder is my understanding correct?  need i set multiple json file in the training script like this:
```
...
    --data_path ./data/LLaMA-VID-Finetune/llava_558k_with_webvid.json;./data/LLaMA-VID-Finetune/llava_v1_5_mix665k_with_video_chatgpt.json;
...
```
Thanks.

**Comment by wcy1122** [comment]
Hi. --data_path ./data/LLaMA-VID-Finetune/llava_558k_with_webvid.json is used for stage 1, ./data/LLaMA-VID-Finetune/llava_v1_5_mix665k_with_video_chatgpt.json is used for stage 2
