### ISSUE TITLE
When can the Customed Long Video Gradio Web UI be released？

### ISSUE THREAD

**Issue by QiSu77** [dvlab-research/LLaMA-VID#40]
HEY,
Since you have released the long video CLI inference, when will you release the Graadio Web UI for customer long video？
I think so many people are looking forward to it!
Thanks!

**Comment by dragen1860** [comment]
I suggest you try the short video gradio demo firstly and then its easy to understand long video pipeline without gradio ui.

**Comment by QiSu77** [comment]
Thanks for your suggestion! But I need it to show my boss.
By the time, when you try the long video CLI inference, did you meet the problem that 
"Loading pretrained weights...
Loading vlm_att_query weights...
Loading vlm_att_ln weights...
Traceback (most recent call last):
  File "/home/deepspeed/multimodal/LLaMA-VID/llamavid/serve/run_llamavid_movie.py", line 113, in <module>
    run_inference(args)
  File "/home/deepspeed/multimodal/LLaMA-VID/llamavid/serve/run_llamavid_movie.py", line 50, in run_inference
    video_info = pickle.load(open(args.video_file, 'rb'))
_pickle.UnpicklingError: invalid load key, '\x00'.
"
It seems something wrong with the .pkl  @dragen1860

**Comment by dragen1860** [comment]
> Thanks for your suggestion! But I need it to show my boss. By the time, when you try the long video CLI inference, did you meet the problem that "Loading pretrained weights... Loading vlm_att_query weights... Loading vlm_att_ln weights... Text with video Traceback (most recent call last): File "/home/deepspeed/multimodal/LLaMA-VID/llamavid/serve/run_llamavid_movie.py", line 113, in run_inference(args) File "/home/deepspeed/multimodal/LLaMA-VID/llamavid/serve/run_llamavid_movie.py", line 73, in run_inference conv = conv_templates[args.conv_mode].copy() KeyError: None " @dragen1860

I guess you maybe give the Empy `conversion template` parameters. It has several given templates defined in code. you should give a specified template parameters.

**Comment by yanwei-li** [comment]
> HEY, Since you have released the long video CLI inference, when will you release the Graadio Web UI for customer long video？ I think so many people are looking forward to it! Thanks!

Hi, we do not have a plan to support customized long videos (means movies). Because it costs a lot of memory and needs to preprocess the movie for frame features and subtitles. You can follow the guidelines in `README/Long Video Inference` to support long movie inference in your own machine. It should be easy to simply modify the given gradio UI.
