### ISSUE TITLE
you build `build_vision_tower` twice?

### ISSUE THREAD

**Issue by dragen1860** [dvlab-research/LLaMA-VID#42]
<img width="879" alt="image" src="https://github.com/dvlab-research/LLaMA-VID/assets/4252555/1370b6cf-a262-4a98-8342-f97a27386e0d">

1. when create the class , build it the first time.
2. after that, you call `initialize_vision_modules` in `train()` in `train.py`.
```
    if model_args.vision_tower is not None:
        model.get_model().initialize_vision_modules(
            model_args=model_args,
            fsdp=training_args.fsdp,
            max_token=training_args.model_max_length
        )
```

i found you build it twice, is my understanding correct?

**Comment by yanwei-li** [comment]
Hi, we use LLaVA as our pipeline. This is the parameter in LLaVA. Please refer to [LLaVA](https://github.com/haotian-liu/LLaVA) for this issue.
