### ISSUE TITLE
A question in stage3

### ISSUE THREAD

**Issue by liziming5353** [dvlab-research/LLaMA-VID#45]
In the stage3 script, why are these two parameters(model_name_or_path, pretrain_mm_mlp_adapter) present at the same time? The former should include the latter, right？

**Comment by dragen1860** [comment]
same question.  I also felt confused. it should load from     --model_name_or_path ./work_dirs/llama-vid-7b-full-224-video-fps-1 .
```
deepspeed llamavid/train/train_mem.py \
    --deepspeed ./scripts/zero2_offload.json \
    --model_name_or_path ./work_dirs/llama-vid-7b-full-224-video-fps-1 \
    --version imgsp_v1 \
    --data_path ./data/LLaMA-VID-Finetune/long_videoqa.json \
    --image_folder ./data/LLaMA-VID-Finetune \
    --video_folder ./data/LLaMA-VID-Finetune \
    --vision_tower ./model_zoo/LAVIS/eva_vit_g.pth \
    --image_processor ./llamavid/processor/clip-patch14-224 \
    --pretrain_mm_mlp_adapter ./work_dirs/llama-vid-7b-pretrain-224-video-fps-1/mm_projector.bin \
```

**Comment by dragen1860** [comment]
let us keep in touch about LLama-VID. add me by wechat: dragen1860 . @liziming5353

**Comment by yanwei-li** [comment]
Thanks for the report. This `pretrain_mm_mlp_adapter ` should be ignored. We update the script.
