### ISSUE TITLE
why different architectures in stage2 and stage3?

### ISSUE THREAD

**Issue by dragen1860** [dvlab-research/LLaMA-VID#46]
Hi, all:
  I found it has different architectures `LlamaForCausalLM or LlavaLlamaAttForCausalLM` in config.json file.
for stage1, the config.json is:
```
{
  "_name_or_path": "model_zoo/LLM/vicuna/7B-V1.5",
  "architectures": [
    "**LlamaForCausalLM**"
  ],
  "bert_type": "qformer_pretrain_freeze",
```

but for stage2, the config.json is :
```
{
  "_name_or_path":  "model_zoo/LLM/vicuna/7B-V1.5",
  "architectures": [
    "**LlavaLlamaAttForCausalLM**"
  ],
  "bert_type": "qformer_pretrain",
```

my question why stage1 use LlamaForCausalLM?

**Comment by yanwei-li** [comment]
Hi, we use LLaVA as our pipeline. This is the function in LLaVA. Please refer to [LLaVA](https://github.com/haotian-liu/LLaVA) for this issue.
