### ISSUE TITLE
why  delay_load in build_vision_tower(config, delay_load=True)?

### ISSUE THREAD

**Issue by dragen1860** [dvlab-research/LLaMA-VID#47]
dear author:
  Q1: I find you can create vision tower in init stage. However, the delay_load=True is really confusing. why create the EVA network without loading?

![image](https://github.com/dvlab-research/LLaMA-VID/assets/4252555/6a7b6760-e254-497e-8fb4-3e4862fb42d1)

Q2: i notice you used both `mm_vision_tower` and `vision_tower` hyperparameters in config, however, I really confused why use these two? are they the same?
![image](https://github.com/dvlab-research/LLaMA-VID/assets/4252555/991d5e54-a194-4637-9675-4612cdbd7b55)

**Comment by yanwei-li** [comment]
Hi, we use LLaVA as our pipeline. This is the function in LLaVA. Please refer to [LLaVA](https://github.com/haotian-liu/LLaVA) for this issue.
