### ISSUE TITLE
Long Video CLI wrong

### ISSUE THREAD

**Issue by QiSu77** [dvlab-research/LLaMA-VID#48]
When I use "   python llamavid/serve/run_llamavid_movie.py --model-path work_dirs/llama-vid/llama-vid-7b-full-224-long-video --video-file ./featuresTest/test.pkl --load-4bit --question 'summarize video information'     "
It is wrong that :
"You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Freezing pretrained qformer weights...
Loading pretrained weights...
Loading vlm_att_query weights...
Loading vlm_att_ln weights...
Text with video
Traceback (most recent call last):
  File "/home/deepspeed/multimodal/LLaMA-VID/llamavid/serve/run_llamavid_movie.py", line 113, in <module>
    run_inference(args)
  File "/home/deepspeed/multimodal/LLaMA-VID/llamavid/serve/run_llamavid_movie.py", line 73, in run_inference
    conv = conv_templates[args.conv_mode].copy()
KeyError: None
”
Is that something wrong with "parser.add_argument("--conv-mode", type=str, default=None)", what should I do ?
thanks!

**Comment by wcy1122** [comment]
Hi, we add the default value of --conv-mode as 'vicuna_v1'. Check our latest code.

**Comment by QiSu77** [comment]
Thanks a lot !
