### ISSUE TITLE
is the LLM weight trainable during stage1-2-3?

### ISSUE THREAD

**Issue by dragen1860** [dvlab-research/LLaMA-VID#49]
Hi, dea author:
 I noticed you have an table describing the weights trainable or not in stage 1-2-3. the vision encoder means EVA and the text decoder means QFormer. However, there is no describe about the LLM  vicuna 7b/13b module.
![image](https://github.com/dvlab-research/LLaMA-VID/assets/4252555/2e17b006-dba6-49c3-a6e6-0e562db44f3b)

please let me know the LLM weights is trainable in each stage? thank you.

**Comment by yanwei-li** [comment]
Hi, LLM is fixed in Stage 1 and open in 2-3.

**Comment by jeasinema** [comment]
Maybe fixing the arxiv paper also, If Text decoder == LLM?
