### ISSUE TITLE
About text encoder

### ISSUE THREAD

**Issue by liziming5353** [dvlab-research/LLaMA-VID#51]
May I ask what changes have been made to the text encoder BertLMHeadModel you are using compared to the original BERT? I cannot fully understand the code and there is no detailed introduction in the paper.

**Comment by yanwei-li** [comment]
Hi, we use the `BertLMHeadModel ` from BLIP2, it mainly supports the pre-defined `query` in the self-attention and cross-attention in BERT, like [this](https://github.com/dvlab-research/LLaMA-VID/blob/c43ea50e2fec1b624d4fd6c3942f147959519da9/llamavid/model/qformer.py#L102).

**Comment by dragen1860** [comment]
@yanwei-li from my perspective, the `Text Decoder` in your paper should actually called `Text Encoder`, but i don't why you can it text decoder. Thank you.

**Comment by yanwei-li** [comment]
Hi, because we adopt the BERT in a decoder manner, which takes images and text as input in cross attention.
