### ISSUE TITLE
why stage 1 and 2 use differenct `    --version plain_guided ` `    --version imgsp_v1 ` parameters?

### ISSUE THREAD

**Issue by dragen1860** [dvlab-research/LLaMA-VID#55]
Dear all:
  why stage 1 and 2 use different `    --version plain_guided ` `    --version imgsp_v1 ` parameters? thank you.

**Comment by yanwei-li** [comment]
Hi, because in stage 1, we do not append instructions before (or after) image tokens to LLM following that in LLaVA. In stage 2, we append user instructions in each conversation turn.
