### ISSUE TITLE
is eva_vit_g.pth trained by yourself?

### ISSUE THREAD

**Issue by Deaddawn** [dvlab-research/LLaMA-VID#56]
Hi, I'm wondering if eva_vit_g.pth(visual encoder in the paper) trained by yourself  or it comes from this paper "https://arxiv.org/pdf/2211.07636.pdf"?

**Comment by dragen1860** [comment]
it comes from `https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth` and keep frozen in all stage 1,2,3 .
