### ISSUE TITLE
MSVD ACC decrease after stage3 

### ISSUE THREAD

**Issue by Deaddawn** [dvlab-research/LLaMA-VID#58]
Hi, there. I have experimented on the MSVD QA using llama-vid-7b-full-224-video-fps-1 and llama-vid-7b-full-224-long-video.  The latter acc decrease, does that make sense to you?

**Comment by Deaddawn** [comment]
decrease about 0.2

**Comment by yanwei-li** [comment]
Hi, this could happen when tuning long videos. And performance of the MSVD QA could also have variant results because of the GPT evaluation.

**Comment by Deaddawn** [comment]
> Hi, this could happen when tuning long videos. And performance of the MSVD QA could also have variant results because of the GPT evaluation.

got it, tks

**Comment by wongtou** [comment]
> decrease about 0.2

@Deaddawn 
Hello, I ran into the same issue. Could I confirm — when you mentioned “0.2,” were you referring to Accuracy?

On the MSVD dataset, using gpt-3.5-turbo for evaluation, I got a score of around 0.69 for the author-provided llama-vid-7b-full-224-video-fps-1 model, while the llama-vid-7b-full-224-long-video model scored around 0.52.

Are your test results roughly in the same range?

**Comment by wongtou** [comment]
@yanwei-li Thanks for your great work on LLaMA-VID! 

Based on my reading of the paper, Stage 3 mainly introduces long-video tuning with MovieNet to support hour-long videos and 64K-token context for plot reasoning and detailed understanding. However, all quantitative results in the paper are reported after Stage 1+2 training only, and Stage 3 may actually hurt performance on short-video benchmarks (e.g., MSVD) due to domain shift or catastrophic forgetting. Its main benefit seems to be long-context reasoning ability, not higher scores on short-video QA. 

Could you confirm if this interpretation is correct?

**Comment by Deaddawn** [comment]
> > decrease about 0.2
> 
> [@Deaddawn](https://github.com/Deaddawn) Hello, I ran into the same issue. Could I confirm — when you mentioned “0.2,” were you referring to Accuracy?
> 
> On the MSVD dataset, using gpt-3.5-turbo for evaluation, I got a score of around 0.69 for the author-provided llama-vid-7b-full-224-video-fps-1 model, while the llama-vid-7b-full-224-long-video model scored around 0.52.
> 
> Are your test results roughly in the same range?

About right

**Comment by wongtou** [comment]
> > > decrease about 0.2
> > 
> > 
> > [@Deaddawn](https://github.com/Deaddawn) Hello, I ran into the same issue. Could I confirm — when you mentioned “0.2,” were you referring to Accuracy?
> > On the MSVD dataset, using gpt-3.5-turbo for evaluation, I got a score of around 0.69 for the author-provided llama-vid-7b-full-224-video-fps-1 model, while the llama-vid-7b-full-224-long-video model scored around 0.52.
> > Are your test results roughly in the same range?
> 
> About right

Thanks

**Comment by Deaddawn** [comment]
> > > > decrease about 0.2
> > > 
> > > 
> > > [@Deaddawn](https://github.com/Deaddawn) Hello, I ran into the same issue. Could I confirm — when you mentioned “0.2,” were you referring to Accuracy?
> > > On the MSVD dataset, using gpt-3.5-turbo for evaluation, I got a score of around 0.69 for the author-provided llama-vid-7b-full-224-video-fps-1 model, while the llama-vid-7b-full-224-long-video model scored around 0.52.
> > > Are your test results roughly in the same range?
> > 
> > 
> > About right
> 
> Thanks

Though it may vary as @yanwei-li said.
