### ISSUE TITLE
error: llava key

### ISSUE THREAD

**Issue by menahem-borges-rodrigues** [dvlab-research/LLaMA-VID#64]
Hey1

I'm encountering an error when trying to download the model from Hugging Face. The error is related to "llava." Are you already integrated with Hugging Face? Should I install a version later than your requirements, or should I proceed to download the model in a different way?

thank you!
![Screenshot from 2024-02-20 16-47-08](https://github.com/dvlab-research/LLaMA-VID/assets/72225662/c560376b-0ba4-4ac3-8f2c-1fd97e2b1612)

**Comment by Kamakshi8104** [comment]
@menahem-borges-rodrigues how did you resolve this?
