### ISSUE TITLE
where is the gradio python file?

### ISSUE THREAD

**Issue by Steven0706** [dvlab-research/LLaMA-VID#7]
where is the gradio python file?

**Comment by yanwei-li** [comment]
Hi Steven, we update the gradio file. Please try it following instructions in README. Thanks~

**Comment by Steven0706** [comment]
> Hi Steven, we update the gradio file. Please try it following instructions in README. Thanks~

thank you. So we need to run the worker+controller+gradio to have your demo's interaction to work, right? thanks

**Comment by yanwei-li** [comment]
Yes, you are right!
