### ISSUE TITLE
About preprocessing movienet

### ISSUE THREAD

**Issue by wangkunyu241** [dvlab-research/LLaMA-VID#9]
In extract_novienet_features.py, there exists one line "shot_path = os.path.join(files_dir, 'shot', f'{imdb_id}.txt')". However, i don't found such shot folder in MovieNet.tar.gz, how can i solve it?

**Comment by wcy1122** [comment]
Hello, the shot.zip can be found [here](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155186668_link_cuhk_edu_hk/EYbaGk86_WNFm9YP45WVQ_oBXR-W3QFvuev66D3ZZm68zw?e=VflPBw).
You can unzip this file and move it to `LLaMA-VID/data/LLaMA-VID-Finetune/movienet/files`.

**Comment by ander1119** [comment]
Hi, the link you provided says "This link has been removed". Could you provide another available link? Thanks!
